export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_INCOME = 'ADD_INCOME';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_INCOME = 'DELETE_INCOME';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
